services:
  snmp-poller:
    build:
      context: .
      dockerfile: dockerfile
    container_name: snmp-poller
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    network_mode: bridge
